# Generated by Django 5.0.4 on 2024-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_actor_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, default='movie_app/static/movie_app/img/actors/i.webp', null=True, upload_to='movie_app/static/movie_app/img/actors'),
        ),
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
